name: Build Java Project

on:
  push:
    branches: [ "principal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Conceder permissão ao Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build com Maven
        run: ./mvnw clean install
